connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dell
  password: dell

development:
  <<: *connection
  database: twitter-clap_development

test:
  <<: *connection
  database: twitter-clap_test

production:
  <<: *connection
  database: twitter-clap_production